//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystemHelpStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fail
    {
        public int IdFail { get; set; }
        public string NameFail { get; set; }
        public string WayToFail { get; set; }
        public int IdTask { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
