//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystemHelpStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filters
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Query { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Color { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
