//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystemHelpStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPriorities
    {
        public int IDTaskPriorities { get; set; }
        public int IdTask { get; set; }
        public string Category { get; set; }
        public string Prioritie { get; set; }
        public string Label { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
