//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystemHelpStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignee
    {
        public int TaskAssigneeId { get; set; }
        public int TaskId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
        public bool IsNew { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Users Users { get; set; }
    }
}
