//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystemHelpStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskFilters
    {
        public int Id { get; set; }
        public int FilterId { get; set; }
        public int TaskId { get; set; }
        public System.DateTime AppliedAt { get; set; }
    
        public virtual Filters Filters { get; set; }
        public virtual Task Task { get; set; }
    }
}
