//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSystemHelpStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInvitation
    {
        public int InvitationId { get; set; }
        public int TeamId { get; set; }
        public int InviterId { get; set; }
        public int InviteeId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsNew { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
